# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20171130_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tarifa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Tarifa'),
            preserve_default=False,
        ),
    ]
