# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_tarifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tarifa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Tarifa'),
        ),
    ]
