# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20171130_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apellido',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='cif',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(default='', max_length=250),
        ),
    ]
