# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20171130_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cif',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
