# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='deuda',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagado',
            field=models.FloatField(default=0),
        ),
    ]
