# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20171123_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='unidades_vendidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='pendiente', max_length=100),
        ),
    ]
