# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('pedidos', '0004_auto_20171130_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ManyToManyField(to='producto.Producto'),
        ),
    ]
