# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20171205_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio_total_unidad',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
