# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_precio_total_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
